services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile  # Make sure this exists
    ports:
      - "5173:5173"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
