deploy:
  name: Deploy Stage
  runs-on: ubuntu-latest
  needs: build

  steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: build-artifacts
        path: .

    - name: Extract artifact
      run: tar -xzf build-artifacts.tar.gz

    - name: Copy files to EC2
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.AWS_HOST }}
        username: ${{ secrets.AWS_USER }}
        key: ${{ secrets.AWS_SSH_KEY }}
        source: "./backend/*,./frontend/*,./docker-compose.yml"
        target: "/home/${{ secrets.AWS_USER }}/app"

    - name: Deploy on EC2
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.AWS_HOST }}
        username: ${{ secrets.AWS_USER }}
        key: ${{ secrets.AWS_SSH_KEY }}
        script: |
          set -e

          # Install Docker if missing
          if ! command -v docker &> /dev/null; then
            echo ">>> Installing Docker..."
            sudo apt-get update -y
            sudo apt-get install -y docker.io
            sudo systemctl enable docker
            sudo systemctl start docker
          fi

          # Install docker-compose if missing
          if ! command -v docker-compose &> /dev/null; then
            echo ">>> Installing docker-compose..."
            sudo curl -L "https://github.com/docker/compose/releases/download/v2.29.7/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
          fi

          echo ">>> Deploying app..."
          cd /home/${{ secrets.AWS_USER }}/app
          sudo docker-compose down || true
          sudo docker-compose up -d --build
